### ISSUE TITLE
PasteScript-1.7.5/ is not Python3 compatible

### ISSUE THREAD

**Issue by clozinski** [zopefoundation/groktoolkit#4]
Both the master branch and the resurrection sprint branch 
buildout.cfg calls grok.cfg calls ztk.cfg which includes 
PasteScript-1.7.5/

The following error messagte is generated  
File "/tmp/easy_install-8ngcunq7/PasteScript-1.7.5/setup.py", line 16
    print 'Warning: no news for this version found'

 But when you look at the ztk.cfg code it says:

    # PasteScript should not be needed anymore, since zope.paste supports serving
    # directly now.
    PasteScript = 1.7.5

So I removed that line, but ran into the next problem.  

pkg_resources.VersionConflict: (zc.buildout 2.9.4 (/home/lozinski/repositories/grok.install/eg\
gs/zc.buildout-2.9.4-py3.4.egg), Requirement.parse('zc.buildout==2.5.0'))

I think it is time for me to start showing up at the sprints.  I have joined the meetup group. 

Warm Regards
Chris

**Comment by prsephton** [comment]
Chris, that's why we have things called "versions".  Otherwise we would all go insane.
I for one, have no need for Python 3 right now.  Nothing against Python 3 (other than the breakages like this one) I just don't need it.

**Comment by janwijbrand** [comment]
`PasteScript` is no longer in the `grok.cfg` nor in zope toolkit's version listing. I think we can close this issue.
