### ISSUE TITLE
Upgrading Grok to Python 3

### ISSUE THREAD

**Issue by clozinski** [zopefoundation/groktoolkit#5]
Well, I am just trying to upgrade grok to Python 3

Let us take 

Z3C.flashmessage as an example

GrokUI requries z3c.flashmessages.
groktoolkit grok.cfg calls for z3c.flashmessages 1.3

But if I look at PyPi, there is Z3c.flashmessages 2.0 released in August 2016. 
 
So maybe the zope stuff is upgraded, much of the z3c stuff is also on Python 3, but the 
grok stuff is not.  

I count 21  grok packages.  Maybe a bit much for me to upgrade by myself. 

So just to be clear, is anyone running Grok on Python 3?  If so, could I please get a copy of your grok.cfg file?

What about Cromlech?  Is the grok compatible version of that on Python 3?

Will anyone else here be at PyCon France?

Warm Regards
Christopher Lozinski

**Comment by icemac** [comment]
There is #2 as a starting point to eventually reach Python 3 compatibility of Grok.

**Comment by clozinski** [comment]
Thank you for that reminder.  Very interesting.  I poked around.  Here is what I think that represents.  
There are versions of the ZTK  that run on Python 3.  That is what the resurrection sprint created.   So that pull request wants to upgrade Grok to use those versions of the ZTK.  That is a big step in the right direction, but it still leaves the problem of porting all of those grok libraries to Python 3.  

Did I get that rigth?

Maybe I do not need all of the grok libraries.  Maybe I can use the cromlech libraries which are already ported to Python 3.   So I took a look at my paster file. 

Grok Libraries I think I use. 
  grokcore.view
  grokcore.security
  grokcore.component
  grokcore.formlib
  megrok.login
  megrok.z3cform.base
  grokcore.annotation
  grokcore.startup
  grokcore.chameleon
  grokui.admin
  grok
  megrok.pagetemplate
  grokui.base
  grokcore.site
  grokcore.content

Grok libraries which I suspect I do not use. 
  grokcore.json
  grokcore.rest
  grokcore.message


Grok libraires which I am pretty sure  I do not use. 
  grokcore.xmlrpc
  grokcore.catalog
  megrok.menu
  grokcore.viewlet
  grokcore.layout

So maybe there are only 15 libraries which I need to upgrade to Python 3.  Not as bad as I thought, but still intimidating.  I am not sure what to do.   Maybe cromlech is a good way to go.

**Comment by clozinski** [comment]
Thank you @icemac for bringing my attention to this problem.  Here is a more careful analysis of upgrading the grok tool kit. 

Well maybe upgrading to Python 3 is not as hard as I thought.  We have a working grokproject.  Then there are the changes from the resurrection sprint to the versions.  That brings us up to something where all the zope files are in Python 3.  Then it turns out I do not use all of Grok.  From grokproject, I do use the following files: 

  grokcore.chameleon
   grokcore.component
   grokcore.content
   grokcore.formlib
   grokcore.security
   grokcore.site
   grokcore.startup
   grokcore.view
   grokui.admin
   grokui.base

The above files are all in Python 2.  Or at least the Changes.txt file does not mention an upgrade to Python 3. 

   martian is already in Python 3.  Thank you someone. 

So at first glance it does not seem so bad. 

Then I checked.  GrokUI.admin uses grokui.base which brings in 
  megrok.menu
   grokcore.message
   grokcore.layout

OUCH 

But I do not think I use the following files. 

   grokcore.viewlet
      grokcore.rest
   grokcore.xmlrpc
   grokcore.json
  grokcore.traverser (I have my own). 
 grokcore.annotation
   grokcore.catalog 

Of course there will be other things pulled in which need to be upgraded.   Well at least I have a handle on the scope of the problem.

**Comment by icemac** [comment]
@clozinski At least `grokcore.component` already supports Python 3, see zopefoundation/grokcore.component#1 and zopefoundation/grokcore.component#9.
Same for zopefoundation/grokcore.annotation#2. The other packages I do not use, so I do not know about them and was to lazy to look their status up.

**Comment by clozinski** [comment]
Thank you. I looked at some of the packages, and made assumptions for the others.  
 I should have checked them all more carefully.  Today I am flying off to Marrakech, but in due course I will go through them all carefully and see what is requited.  Maybe I should even  make the list part of this repository.

**Comment by janwijbrand** [comment]
Just to note, I'm trying to get a bit more migration moving on the https://github.com/zopefoundation/groktoolkit/pull/2 branch

**Comment by janwijbrand** [comment]
By lack of a better place to keep track of my progress:

* I released `grokcore.security`
* I released `grokcore.view`

Both releases unblock working on subsequent packages in the `grokcore.*` namespace. I feel there's still inconsistencies in the `travis.yml`, `tox.ini` and `setup.py` files and version numbering for the different `grokcore.*` package; I think we can resolve that later.

**Comment by janwijbrand** [comment]
Next up is `grokcore.content` that is blocking working on `grokcore.formlib`.

**Comment by janwijbrand** [comment]
`grokcore.content` and `grokcore.formlib` done. Not onto `grokcore.rest` which requires updating `zope.errorview` which requires updating (or replacing) `z3c.recipe.i18n`.

**Comment by PythonLinks** [comment]
Thank you for all of the hard work. 
Does this mean that soon grok and grokproject will all run on Python 3?
I thought there were a lot of packages which needed to be updated.

**Comment by janwijbrand** [comment]
@PythonLinks that's the goal. How "soon" this will be done, I do not know. There's still a fair amount of grokcore.* packages to deal with still, but we're getting there.

**Comment by janwijbrand** [comment]
I gave up on `z3c.recipe.i18n` for now. It is stalled by not being able to run tox-based tests nor travis running tests due to (I understand) a bug in pip preventing it to install the required `zc.recipe.egg`. I'll comment out the buildout parts in `zope.errorview` that invoke `z3c.recipe.i18n`. This allows me (I think) to keep moving forward.

**Comment by janwijbrand** [comment]
Turns out there was a way to get tests to run for `z3c.recipe.egg` after all. But it also turned out `zope.errorview` was already fixed and released for Python 3.

**Comment by janwijbrand** [comment]
fixed `grokcore.viewlet` and released it. Fixed `grokcore.site` too (but not merged/released yet).

**Comment by janwijbrand** [comment]
`grokcore.site`, `grokcore.catalog`, `grokcore.view` (again) done. Now on `grokcore.traverser` (that depended on `grokcore.rest` that depends on `grokcore.traverser` - I broke that circular dependency just now).

**Comment by janwijbrand** [comment]
I'm strugling with getting `grokcore.rest` to work. It would be great if someone still using `grokcore.rest` to have a look at it too.

**Comment by clozinski** [comment]
I am so impressed by what you are doing. 
I am happy to help. 
What can I do?  
lozinski@Pythonlinks.info

**Comment by janwijbrand** [comment]
We need a merge/release of `z3c.recipe.i18n` after all to unblock a merge/release of `zope.errorview` to unblock a merge/release of `grokcore.rest`. In the meantime we're down to this list still to do:

    5 failure(s).
    - test-grok-grokcore.json
    - test-grok-grokcore.xmlrpc
    - test-grok-grokcore.layout
    - test-grok-grokcore.message
    - test-grok-grokcore.startup

**Comment by janwijbrand** [comment]
`z3c.recipe.i18n`, `zope.errorview` and `grokcore.rest` done. `grokcore.json` done too. We're not at:

    4 failure(s).
    - test-grok-grokcore.xmlrpc
    - test-grok-grokcore.layout
    - test-grok-grokcore.message
    - test-grok-grokcore.startup

**Comment by janwijbrand** [comment]
`grokcore.xmlprc` done. Now at:

    3 failure(s).
    - test-grok-grokcore.layout
    - test-grok-grokcore.message
    - test-grok-grokcore.startup

**Comment by janwijbrand** [comment]
`grokcore.layout` done. Down to:

    2 failure(s).
    - test-grok-zope.fanstatic
    - test-grok-grokcore.message

**Comment by janwijbrand** [comment]
`grokcore.layout` done. Down to:

    2 failure(s).
    - test-grok-zope.fanstatic
    - test-grok-grokcore.message

**Comment by janwijbrand** [comment]
Still `zope.fanstatic` and grok and `grokcore.message` to do. Still, all the `grokcore.*` packages got an overhaul as not all tests were picked up by Travis. This is now fixed.

**Comment by janwijbrand** [comment]
`grokcore.message` done, `grokcore.error` added, `zope.errorview` re-fixed, `grok` done, `zope.fanstatic` and `fanstatic` done. Only thing left now is getting the test infra for `groktoolkit` itself done. Well, that, and reconsidering what to do with `megrok.*` and `grokui.*`.

**Comment by janwijbrand** [comment]
Note that @gyst is working on getting the test infra set up. See https://github.com/gyst/groktoolkit/tree/resurrection-python3

**Comment by janwijbrand** [comment]
Yay.

    > ./bin/test-grok
    Running test-grok-z3c.autoinclude
    Running test-grok-grok
    Running test-grok-grokcore.view
    Running test-grok-grokcore.formlib
    Running test-grok-grokcore.security
    Running test-grok-grokcore.chameleon
    Running test-grok-grokcore.viewlet
    Running test-grok-grokcore.rest
    Running test-grok-grokcore.traverser
    Running test-grok-grokcore.json
    Running test-grok-grokcore.layout
    Running test-grok-grokcore.component
    Running test-grok-grokcore.startup
    Running test-grok-grokcore.xmlrpc
    Running test-grok-z3c.flashmessage
    Running test-grok-zope.errorview
    Running test-grok-grokcore.message
    Running test-grok-grokcore.catalog
    Running test-grok-grokcore.error
    Running test-grok-grokcore.annotation
    Running test-grok-martian
    Running test-grok-grokcore.content
    Running test-grok-grokcore.site
    Running test-grok-z3c.evalexception
    0 failure(s).

**Comment by janwijbrand** [comment]
We're now at a point where I all the `grok.* ` is indeed done. There're some packages missing from this effort, meaning `grokui.admin`, `grokui.base` and `megrok.menu`. It would be nice if someone using those packages could lend a hand at porting those. The `grokcore.*` packages should provide ample inspiration how to do this.

**Comment by janwijbrand** [comment]
I've released groktoolkit 3.0.0a1 (!!). This release it missing `grokui.*` and `megrok.menu`, but at least enables us to get rid of the buildout extends URLs pointing to a branch. I'll update those now for the `grokcore.*` packages.

**Comment by janwijbrand** [comment]
All the extends URLs in the `grokcore.*` packages have been updated.
